---
version: 0.0.14
files:
  package.json: '"version": "%.%.%",'
  bower.json: '"version": "%.%.%",'
  Gruntfile.coffee: currentVersion = 'v%.%.%'
  README.md: '[latest API documentation Page](http://cureapp.github.io/loopback-promised/doc/v%.%.%/index.html)'
