---
version: 0.0.10
files:
  package.json: '"version": "%.%.%",'
  bower.json: '"version": "%.%.%",'
  Gruntfile.coffee: "currentVersion = 'v%.%.%'"
  README.md: "[latest API documentation Page](https://cureapp.github.io/loopback-promised/doc/v%.%.%/index.html)"
